<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>NoteTaking</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\s*((//).*$\n?)</string>
			<key>name</key>
			<string>comment.line.double-slash.NoteTaking</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\s*((~).*$\n?)</string>
			<key>name</key>
			<string>entity.name.function.NoteTaking</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>˙</string>
			<key>end</key>
			<string>˙</string>
			<key>name</key>
			<string>string.quoted.double.NoteTaking</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.NoteTaking</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\*</string>
			<key>end</key>
			<string>\*|\n</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.NoteTaking</string>
	<key>uuid</key>
	<string>FB7889E9-6E33-497E-BCF8-91860D0993FB</string>
</dict>
</plist>
