<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>name</key>
		<string>NoteTaking</string>

		<key>patterns</key>
		<array>


			<dict>
				<key>match</key>
				<string>(\s*((//).*$\n?))</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>comment</string>
					</dict>
				</dict>
			</dict>


			<dict>
				<key>match</key>
				<string>(\s*((~).*$\n?))</string>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>entity.name.function.python</string>
					</dict>
				</dict>
			</dict>


			<dict>
				<key>patterns</key>
				<array>
					<dict>

						<key>begin</key>
						<string>~</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>string</string>
							</dict>
						</dict>

						<key>end</key>
						<string>•|\n</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>string</string>
							</dict>
						</dict>

						<key>name</key>
						<string>string</string>
					</dict>
				</array>
			</dict>


			<dict>
				<key>patterns</key>
				<array>
					<dict>

						<key>begin</key>
						<string>˙</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>string</string>
							</dict>
						</dict>

						<key>end</key>
						<string>˙</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>string</string>
							</dict>
						</dict>

						<key>name</key>
						<string>string</string>
					</dict>
				</array>
			</dict>


				<dict>
				<key>patterns</key>
				<array>
					<dict>

						<key>begin</key>
						<string>/\*</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>comment</string>
							</dict>
						</dict>

						<key>end</key>
						<string>\*/</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>comment</string>
							</dict>
						</dict>

						<key>name</key>
						<string>comment</string>
					</dict>
				</array>
			</dict>


			<dict>
				<key>patterns</key>
				<array>
					<dict>

						<key>begin</key>
						<string>\*</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>keyword</string>
							</dict>
						</dict>

						<key>end</key>
						<string>•|\n</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>keyword</string>
							</dict>
						</dict>

						<key>name</key>
						<string>keyword</string>
					</dict>
				</array>
			</dict>


		</array>
		<key>scopeName</key>
		<string>NoteTaking</string>
	</dict>
</plist>